# Generated by Django 2.2.4 on 2019-08-27 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_auto_20190826_0909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pages',
            new_name='Page',
        ),
    ]
